New Button and Small Changes
AinaVT/LethalConfig pull request #53
Opened 2024-09-11 18:28 UTC by darmuh

Sending PR from fork

2024-09-12 04:56 UTC, AinaVT commented on LethalConfig.zip
Could you remove this zip file with the compiled plugin?

2024-09-12 04:57 UTC, AinaVT commented on README.md
Could you remove this or move this to the CHANGELOG for a new version?

2024-09-12 05:00 UTC, AinaVT commented on Assets/Scenes/TestDarmuh.unity
Could you remove this and the associated meta file?

2024-09-12 05:01 UTC, AinaVT requested changes
Nice stuff! Just waiting for you to address the comments, mainly just to remove unnecessary files (like the zip with the binaries).

2024-09-12 06:05 UTC, darmuh commented on LethalConfig.zip
Will do, only added them so I could link others to test it out (without posting to thunderstore)

2024-09-12 06:06 UTC, darmuh commented on README.md
Changelog should have the same changes mentioned already. Will remove from readme

2024-09-12 06:06 UTC, darmuh commented on Assets/Scenes/TestDarmuh.unity
Removing them from the repository, was using this scene to test my additions/changes (to not mess with other scenes)

2024-09-12 06:08 UTC, darmuh commented
Glad to see you found no real issues! I've made the requested changes. Let me know if you need anything else 👍

2024-09-13 05:03 UTC, AinaVT approved these changes
Looks good. Will merge and properly test tomorrow or saturday. If I find any issues i'll get on it.
Thank you!

2024-09-13 05:04 UTC, merged